nohup ./TmCryst macros/specsource_0.mac &
nohup ./TmCryst macros/specsource_1.mac &
nohup ./TmCryst macros/specsource_2.mac &
nohup ./TmCryst macros/specsource_3.mac &
nohup ./TmCryst macros/specsource_4.mac &
nohup ./TmCryst macros/specsource_5.mac &
nohup ./TmCryst macros/specsource_6.mac &
nohup ./TmCryst macros/specsource_7.mac &
nohup ./TmCryst macros/specsource_8.mac &
nohup ./TmCryst macros/specsource_9.mac &
